### ISSUE TITLE
How to use maki icon in layout:{ }

### ISSUE THREAD

**Issue by hoogw** [mapbox/maki#463] opened 2019-05-29 17:12 UTC
I install maki by 
                                    npm install @mapbox/maki --save

Then 
I add geojson layer,  want to use icon wetland, as below, 

         
                  "layout": {
                                             "icon-image": "wetland-11",
                                        }

It is not working! But only monument works.  Why????

                                 "layout": {
                                             "icon-image": "monument-11",
                                        }

**Comment by tristen** [comment] 2019-05-29 17:17
Dupe of https://github.com/mapbox/maki/issues/455

**Closed by tristen** 2019-05-29 17:17 UTC
