### ISSUE TITLE
localized hot-spring

### ISSUE THREAD

**Issue by vknoppkewetzel** [mapbox/maki#509] opened 2021-02-26 17:28 UTC
Create localized hot-spring for Japan

inspo:
<img width="129" alt="Screen Shot 2021-01-20 at 10 03 30 AM" src="https://user-images.githubusercontent.com/7087091/109224164-93dea900-7789-11eb-97a7-ff17e495d15c.png">

**Comment by tristen** [comment] 2021-02-26 17:34
Dupe of #502

**Closed by tristen** 2021-02-26 17:34 UTC
Labels: icon request
